steps:
# Clone the repository.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch',
         '$_BRANCH', '$_REPO_URL',
         '--depth', '1',
         '--verbose']
  id: 'Clone Repository'

- name: 'gcr.io/gcp-ml-172005/cb-tfx:latest'
  entrypoint: python
  args: ['-m', 'pytest', '.']
  dir: 'taxi-model-pipeline/tfx-pipeline/models'
  id: 'Unit Test'
  waitFor: ['Clone Repository']

- name: 'gcr.io/gcp-ml-172005/cb-tfx:latest'
  entrypoint: 'tfx'
  args: ['pipeline', 'compile',
          '--pipeline-path', 'kubeflow_v2_runner.py',
          '--engine', 'vertex',
        ]
  dir: 'taxi-model-pipeline/tfx-pipeline'
  id: 'Compile Pipeline'
  waitFor: ['Unit Test']

- name: 'gcr.io/gcp-ml-172005/cb-tfx:latest'
  entrypoint: 'tfx'
  args: ['pipeline', 'create',
          '--pipeline-path', 'kubeflow_v2_runner.py',
          '--engine', 'vertex',
          '--build-image'
        ]
  dir: 'taxi-model-pipeline/tfx-pipeline'
  id: 'Create Pipeline'
  waitFor: ['Compile Pipeline']  

# --project=gcp-ml-172005 --region=us-central1
- name: 'gcr.io/gcp-ml-172005/cb-tfx:latest'
  entrypoint: 'tfx'
  args: ['run', 'create',
          '--engine', 'vertex',
          '--pipeline-name', '$_PIPELINE_NAME',
          '--project', '$_PROJECT',
          '--region', '$_REGION'
        ]
  dir: 'taxi-model-pipeline/tfx-pipeline'
  id: 'Create Pipeline Run'
  waitFor: ['Create Pipeline']