steps:
- name: 'gcr.io/cloud-builders/git'
  args: ...
  id: 'Clone Repository'

# There are three tests are included in models directory
- name: 'gcr.io/$_PROJECT/cb-tfx:latest'
  entrypoint: python
  args: ['-m', 'pytest', '.']
  dir: 'Model-Training-as-a-CI-CD-System/tfx-pipeline/models'
  id: 'Unit Test'
  waitFor: ['Clone Repository']

- name: 'gcr.io/$_PROJECT/cb-tfx:latest'
  entrypoint: 'tfx'
  args: ['pipeline', 'create',
          '--pipeline-path', 'kubeflow_v2_runner.py',
          '--engine', 'vertex',
          '--build-image']
  dir: 'Model-Training-as-a-CI-CD-System/tfx-pipeline'
  id: 'Clone Repository'
  waitFor: ['Compile Pipeline']  

- name: 'gcr.io/$_PROJECT/cb-tfx:latest'
  entrypoint: 'tfx'
  args: ['run', 'create',
          '--engine', 'vertex',
          '--pipeline-name', '$_PIPELINE_NAME',
          '--project', '$_PROJECT',
          '--region', '$_REGION']
  dir: 'Model-Training-as-a-CI-CD-System/tfx-pipeline'
  id: 'Create Pipeline Run'
  waitFor: ['Create Pipeline']