on:
  push:
     branches: [ main ]

env:
  PROJECT: automated-training
  PIPELINE_NAME: tfx-pipeline
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with: 
          version: '286.0.0'
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
          # set up GCP credentials for your Service Account

      - name: trigger cloud build based on pipeline changes
        run: |
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT/$PIPELINE_NAME:$GITHUB_SHA" \
            --machine-type=n1-highcpu-8