on:
  push:
     branches: [ main ]

env:
  SUBSTITUTIONS: "
            _PROJECT=automated-training,\
            _REGION=us-central1,\
            _REPO_URL=https://github.com/fsosap/taxi-model-pipeline,\
            _BRANCH=main,\
            _PIPELINE_NAME=tfx-pipeline
            "  
  
jobs:
  job_id:
      runs-on: ubuntu-latest
      steps:
      - name: 'Checkout to repository'
        uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.RUN_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
