on:
  push:
     branches: [ main ]

env:
  SUBSTITUTIONS: "
            _PROJECT=automated-training,\
            _REGION=us-central1,\
            _REPO_URL=https://github.com/fsosap/taxi-model-pipeline,\
            _BRANCH=main,\
            _PIPELINE_NAME=tfx-pipeline
            "  
  
jobs:
  job_id:
      runs-on: ubuntu-latest

      steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.RUN_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: trigger cloud build based on pipeline changes
        run: |
            gcloud builds submit --no-source --timeout=60m \
            --substitutions $SUBSTITUTIONS \
            --machine-type=n1-highcpu-8