on:
  push:
     branches: [ main ]

env:
  SUBSTITUTIONS: "
   _PROJECT=$automated-training,\
   _REGION=us-central1,\
   _REPO_URL=https://github.com/fsosap/taxi-model-pipeline.git,\
   _BRANCH=main,\
   _PIPELINE_NAME=tfx-pipeline
  "

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with: 
          version: '286.0.0'
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
          # set up GCP credentials for your Service Account

      - name: check if tfx-pipeline folder has anything changed
        uses: dorny/paths-filter@v2.2.1
        id: tfx-pipeline-change
        with:
            filters: |
                src:
                  - 'tfx-pipeline/**'

      - name: trigger cloud build based on pipeline changes
        if: steps.tfx-pipeline-change.outputs.src == 'true'
        run: |
          gcloud builds submit --no-source --timeout=60m \
          --config build/pipeline-deployment.yaml \
          --substitutions $SUBSTITUTIONS \
          --machine-type=n1-highcpu-8